// automatically generated by the FlatBuffers compiler, do not modify

namespace FlatBuffers.Schema.Tests
{

using System;
using FlatBuffers;

public struct PingListItem : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PingListItem GetRootAsPingListItem(ByteBuffer _bb) { return GetRootAsPingListItem(_bb, new PingListItem()); }
  public static PingListItem GetRootAsPingListItem(ByteBuffer _bb, PingListItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PingListItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PingListItem> CreatePingListItem(FlatBufferBuilder builder,
      int key = 0,
      int value = 0) {
    builder.StartObject(2);
    PingListItem.AddValue(builder, value);
    PingListItem.AddKey(builder, key);
    return PingListItem.EndPingListItem(builder);
  }

  public static void StartPingListItem(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddKey(FlatBufferBuilder builder, int key) { builder.AddInt(0, key, 0); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(1, value, 0); }
  public static Offset<PingListItem> EndPingListItem(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PingListItem>(o);
  }
};


}
