// automatically generated by the FlatBuffers compiler, do not modify

namespace FlatBuffers.Schema
{

using System;
using FlatBuffers;

public struct MessageEnvelope : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MessageEnvelope GetRootAsMessageEnvelope(ByteBuffer _bb) { return GetRootAsMessageEnvelope(_bb, new MessageEnvelope()); }
  public static MessageEnvelope GetRootAsMessageEnvelope(ByteBuffer _bb, MessageEnvelope obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MessageEnvelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Type { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetTypeBytes() { return __p.__vector_as_arraysegment(4); }
  public byte Body(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int BodyLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ArraySegment<byte>? GetBodyBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<MessageEnvelope> CreateMessageEnvelope(FlatBufferBuilder builder,
      StringOffset typeOffset = default(StringOffset),
      VectorOffset bodyOffset = default(VectorOffset)) {
    builder.StartObject(2);
    MessageEnvelope.AddBody(builder, bodyOffset);
    MessageEnvelope.AddType(builder, typeOffset);
    return MessageEnvelope.EndMessageEnvelope(builder);
  }

  public static void StartMessageEnvelope(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddType(FlatBufferBuilder builder, StringOffset typeOffset) { builder.AddOffset(0, typeOffset.Value, 0); }
  public static void AddBody(FlatBufferBuilder builder, VectorOffset bodyOffset) { builder.AddOffset(1, bodyOffset.Value, 0); }
  public static VectorOffset CreateBodyVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static void StartBodyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<MessageEnvelope> EndMessageEnvelope(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MessageEnvelope>(o);
  }
  public static void FinishMessageEnvelopeBuffer(FlatBufferBuilder builder, Offset<MessageEnvelope> offset) { builder.Finish(offset.Value); }
};


}
