// automatically generated by the FlatBuffers compiler, do not modify

namespace FlatBuffers.Schema.Tests
{

using System;
using FlatBuffers;

public struct PingListItem : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PingListItem GetRootAsPingListItem(ByteBuffer _bb) { return GetRootAsPingListItem(_bb, new PingListItem()); }
  public static PingListItem GetRootAsPingListItem(ByteBuffer _bb, PingListItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PingListItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PingListItem> CreatePingListItem(FlatBufferBuilder builder,
      int key = 0,
      int value = 0) {
    builder.StartObject(2);
    PingListItem.AddValue(builder, value);
    PingListItem.AddKey(builder, key);
    return PingListItem.EndPingListItem(builder);
  }

  public static void StartPingListItem(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddKey(FlatBufferBuilder builder, int key) { builder.AddInt(0, key, 0); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(1, value, 0); }
  public static Offset<PingListItem> EndPingListItem(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PingListItem>(o);
  }
};

public struct PingList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PingList GetRootAsPingList(ByteBuffer _bb) { return GetRootAsPingList(_bb, new PingList()); }
  public static PingList GetRootAsPingList(ByteBuffer _bb, PingList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PingList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Ticks { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PingListItem? Items(int j) { int o = __p.__offset(6); return o != 0 ? (PingListItem?)(new PingListItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<PingList> CreatePingList(FlatBufferBuilder builder,
      int ticks = 0,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartObject(2);
    PingList.AddItems(builder, itemsOffset);
    PingList.AddTicks(builder, ticks);
    return PingList.EndPingList(builder);
  }

  public static void StartPingList(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddTicks(FlatBufferBuilder builder, int ticks) { builder.AddInt(0, ticks, 0); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(1, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<PingListItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PingList> EndPingList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PingList>(o);
  }
};

public struct PingMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PingMessage GetRootAsPingMessage(ByteBuffer _bb) { return GetRootAsPingMessage(_bb, new PingMessage()); }
  public static PingMessage GetRootAsPingMessage(ByteBuffer _bb, PingMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PingMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Count { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Msg { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetMsgBytes() { return __p.__vector_as_arraysegment(6); }
  public PingList? Lists(int j) { int o = __p.__offset(8); return o != 0 ? (PingList?)(new PingList()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ListsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<PingMessage> CreatePingMessage(FlatBufferBuilder builder,
      int count = 0,
      StringOffset msgOffset = default(StringOffset),
      VectorOffset listsOffset = default(VectorOffset)) {
    builder.StartObject(3);
    PingMessage.AddLists(builder, listsOffset);
    PingMessage.AddMsg(builder, msgOffset);
    PingMessage.AddCount(builder, count);
    return PingMessage.EndPingMessage(builder);
  }

  public static void StartPingMessage(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(0, count, 0); }
  public static void AddMsg(FlatBufferBuilder builder, StringOffset msgOffset) { builder.AddOffset(1, msgOffset.Value, 0); }
  public static void AddLists(FlatBufferBuilder builder, VectorOffset listsOffset) { builder.AddOffset(2, listsOffset.Value, 0); }
  public static VectorOffset CreateListsVector(FlatBufferBuilder builder, Offset<PingList>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartListsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PingMessage> EndPingMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PingMessage>(o);
  }
};

public struct PongMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PongMessage GetRootAsPongMessage(ByteBuffer _bb) { return GetRootAsPongMessage(_bb, new PongMessage()); }
  public static PongMessage GetRootAsPongMessage(ByteBuffer _bb, PongMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PongMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Count { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Msg { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetMsgBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<PongMessage> CreatePongMessage(FlatBufferBuilder builder,
      int count = 0,
      StringOffset msgOffset = default(StringOffset)) {
    builder.StartObject(2);
    PongMessage.AddMsg(builder, msgOffset);
    PongMessage.AddCount(builder, count);
    return PongMessage.EndPongMessage(builder);
  }

  public static void StartPongMessage(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(0, count, 0); }
  public static void AddMsg(FlatBufferBuilder builder, StringOffset msgOffset) { builder.AddOffset(1, msgOffset.Value, 0); }
  public static Offset<PongMessage> EndPongMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PongMessage>(o);
  }
};


}
